카카오 로그인, JWT 토큰 설정
TwoDotFive/server pull request #5
Opened 2024-07-26 05:42 UTC by SEONMl

### 기능 구현
- 회원가입 및 로그인 구현
  - 이름, 닉네임과 프로필 사진은 정책이 정확하지 않아서 일단 냅둠
- JWT access token, refresh token(관련 기능 아직 없음) 발급
- 필터로 인가 관리
  - 인가관련 Exception에 따른 커스텀 필요 (현재 500에러)

토큰 유효O
![스크린샷 2024-07-26 140056](https://github.com/user-attachments/assets/cb5aa2ee-0d0d-4125-b4ea-a936dcf66d9d)

토큰 유효X
![image](https://github.com/user-attachments/assets/1d6bf97a-008c-49d4-ae7a-9344a61a05e3)

### 추가사항
- FindUserProfileServiceImpl 수정함
  - 회원 중복 확인을 eamil로 확인하도록
- UserProfileView 이거 이렇게 쓰는 거 맞는지 확인 좀 ㅎ;;

2024-07-27 18:07 UTC, csct3434 requested changes
https://velog.io/@sunnamgung8/Security-%EC%82%AC%EC%9A%A9%EC%9E%90-%EA%B4%80%EB%A6%AC#userdetails

보통 도메인 엔티티에 시큐리티 코드 안넣을려고 UserDetails 구현체는 따로 작성하는 걸로 알고있어

2024-07-27 18:07 UTC, csct3434 commented on src/main/java/com/example/temp/common/filter/JwtAuthenticationFilter.java
> +                String email = jwtTokenService.extractEmail(token);
email은 추출되고 안쓰이고 있네용

2024-07-27 18:07 UTC, csct3434 commented on src/main/java/com/example/temp/user/controller/OAuthController.java
> +    }
로그인 페이지 주소 응답하는 컨트롤러라서 userDetails는 필요 없는듯

2024-07-27 18:07 UTC, csct3434 commented on src/main/java/com/example/temp/user/service/impl/CreateUserServiceImpl.java
> +        findUser.updateProfile(oAuthResponse.getName(), oAuthResponse.getProfileImageUrl());
아직 와이어프레임에 닉네임, 아이디, 프로필사진 설정하는 화면 없어서 일단 이렇게 해놓은건가?

2024-07-27 18:07 UTC, csct3434 commented on src/main/java/com/example/temp/user/service/impl/CreateUserServiceImpl.java
> +    }
JwtService에 'JwtToken createTokens(User user)' 메서드 만들어서 리팩토링하면 좋을듯

2024-07-27 18:07 UTC, csct3434 commented on src/main/java/com/example/temp/user/domain/value/PlatformType.java
> +}
Enum에서 제공하는 valueOf()랑 getName() 안쓰고 직접 구현한 이유가 있나?

2024-07-27 18:07 UTC, csct3434 commented on src/main/java/com/example/temp/user/service/impl/JwtTokenService.java
> +    }
이 메서드는 용도가 뭐야?

2024-07-27 18:07 UTC, csct3434 commented on src/main/java/com/example/temp/user/service/impl/OAuthService.java
> +        OAuthUrlBuilder urlBuilder = factory.getOAuthURLBuilder();
urlBuilder 안쓰이고 있는듯?

2024-07-27 18:07 UTC, csct3434 commented on src/main/java/com/example/temp/user/service/impl/UserDetailsServiceImpl.java
> +    }
User 엔티티에 PlatformType 있는거 보면 여러 플랫폼 지원한다는 가정하에 설계한거 같은데, 여러 플랫폼에서 같은 이메일 쓰고있는 사람도 있어서 email로는 유일 식별 못할거야.. 나도 카카오 계정에서 네이버 이메일 쓰고 있음

이래서 자연키 대신 인조키 쓰라는듯

2024-07-27 18:07 UTC, csct3434 commented on src/main/java/com/example/temp/user/service/oauth/kakao/KakaoProfileClient.java
> +    }
Webflux는 내가 몰라서..

2024-07-27 18:07 UTC, csct3434 commented on src/main/java/com/example/temp/user/service/oauth/kakao/OAuthKakaoAdapter.java
> +                    .name(profile.getKakaoAccount().getProfile().getNickname())
실명이랑 헷갈릴 수 있어서 nickname으로 바꾸는게 좋을듯

2024-07-27 18:07 UTC, csct3434 commented on src/main/java/com/example/temp/user/domain/User.java
> +    private PlatformType platformType;
Enum 타입은 기본값이 ORDINAL이라 따로 지정 안해주면 숫자로 저장됨
문자로 저장할거면 @Enumerated(value = EnumType.STRING) ㄱㄱ

2024-07-28 08:20 UTC, csct3434 commented on src/main/java/com/example/temp/user/domain/UserRepository.java
> +		return findByEmail(email).orElseThrow(() -> new CustomException(HttpStatus.NOT_FOUND, "회원 조회 실패"));
이런 변경사항은 findByEmailOrElseThrow() 메서드 따로 만들어서 작성해줘

2024-07-29 01:28 UTC, SEONMl commented on src/main/java/com/example/temp/user/controller/OAuthController.java
> +    }
오.. 왜 저렇게 짰지

2024-07-29 01:28 UTC, SEONMl commented on src/main/java/com/example/temp/user/service/impl/CreateUserServiceImpl.java
> +        findUser.updateProfile(oAuthResponse.getName(), oAuthResponse.getProfileImageUrl());
넵 일단은요

2024-07-29 01:30 UTC, SEONMl commented on src/main/java/com/example/temp/user/domain/value/PlatformType.java
> +}
valueOf("kakao") 하니까 인식이 안 돼서요..

2024-07-29 01:35 UTC, SEONMl commented on src/main/java/com/example/temp/user/service/impl/OAuthService.java
> +        OAuthUrlBuilder urlBuilder = factory.getOAuthURLBuilder();
맞네요

2024-07-29 01:35 UTC, SEONMl commented on src/main/java/com/example/temp/user/service/oauth/kakao/KakaoProfileClient.java
> +    }
https://www.baeldung.com/spring-webclient-resttemplate
https://tecoble.techcourse.co.kr/post/2021-07-25-resttemplate-webclient/

비동기 호출 때문에 RestTemplate보단 WebClient 사용하는 걸 권고한다고 합니더

2024-07-29 01:36 UTC, SEONMl commented on src/main/java/com/example/temp/user/service/oauth/kakao/OAuthKakaoAdapter.java
> +                    .name(profile.getKakaoAccount().getProfile().getNickname())
굿

2024-07-29 01:36 UTC, SEONMl commented on src/main/java/com/example/temp/user/domain/User.java
> +    private PlatformType platformType;
확인

2024-07-29 01:37 UTC, SEONMl commented on src/main/java/com/example/temp/user/service/impl/UserDetailsServiceImpl.java
> +    }
글쿠만요 JWT에 인조ID 클레임 넣고 식별하는 방법으로 바꾸먼 될까?

2024-07-29 01:41 UTC, SEONMl commented on src/main/java/com/example/temp/user/service/impl/JwtTokenService.java
> +    }
로그아웃 했을 때 토큰 만료됐다고 알리기 위함을 의도했는데 생각해보니 안 쓸 것 같습니다 필터에서 처리하면 될 듯

2024-07-30 05:05 UTC, csct3434 reviewed
findByPlatformId()랑 findByEmail() 외에는 문제 없어보여요
이 부분만 수정하고 merge하면 좋을거 같습니당 :)

2024-07-30 05:05 UTC, csct3434 commented on src/main/java/com/example/temp/user/domain/UserRepository.java
> +    }
findByPlatformTypeAndPlatformId() 혹은 findByPlatformTypeAndEmail()로 해야 유일 식별이 되지 않을까 싶습니당

2024-07-30 05:05 UTC, csct3434 commented on src/main/java/com/example/temp/common/config/SecurityConfig.java
> +                                .anyRequest().permitAll()
굿굿

2024-07-30 05:05 UTC, csct3434 commented on src/main/java/com/example/temp/user/domain/value/PlatformType.java
> -    }
이렇게 되면 name 필드도 필요 없어진듯 ㅋㅋ

unused import문 'control + option + o'로 정리해 주시면 감사하겠습니다 (__)

2024-07-30 05:37 UTC, SEONMl commented on src/main/java/com/example/temp/user/domain/UserRepository.java
> +    }
넵스바리

2024-07-30 05:38 UTC, SEONMl commented on src/main/java/com/example/temp/user/domain/value/PlatformType.java
> -    }
🤣

2024-07-30 06:23 UTC, csct3434 approved these changes
고생 많으셨습니다 🚀

2024-07-30 06:29 UTC, merged